[env:esp32dev]
board = esp32dev
framework = arduino
monitor_speed = 115200
platform= https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
extra_scripts = pre:scripts/patch_vespa.py

lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
    https://github.com/RoboCore/RoboCore_Vespa.git
board_microros_distro = humble
board_microros_transport = wifi
